name: Build and Publish Data Processing Image

on:
  workflow_call:
    inputs:
      tag:
        description: The docker tag to publish with
        required: true
        default: latest
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: The docker tag to publish with
        required: true
        default: latest
        type: string


env:
  DISTRO: ubuntu
  REGISTRY: ghcr.io
  RC_REGISTRY_IMAGE_NAME: ghcr.io/${{ github.repository }}/rc/data_processing
  FBPCF_VERSION: 2.1.69

jobs:
  build_data_processing_image:
    name: Build Data Processing Image
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-data-processing-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-data-processing

      - name: Pull FBPCF Image
        run: docker pull ghcr.io/facebookresearch/fbpcf/ubuntu:${{ env.FBPCF_VERSION }}

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build EMP Games image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/data_processing/Dockerfile.ubuntu
          tags: |
            ${{ env.RC_REGISTRY_IMAGE_NAME }}:${{ github.event.inputs.tag }}
            ${{ env.RC_REGISTRY_IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            os_release=20.04
            fbpcf_image=ghcr.io/facebookresearch/fbpcf/ubuntu:${{ env.FBPCF_VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # This ugly bit is necessary or else our cache will grow forever
      # until it hits GitHub's limit of 5GB.
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
