name: Build OneDocker image

on:
  workflow_dispatch:

env:
  DISTRO: ubuntu
  TIME_RANGE: 24 hours

jobs:
  ### Build data processing image
  build_data_processing_image:
    name: Build Image
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Remove unused images
        run: |
          df -h
          docker image prune -af
          df -h

      - name: Build onedocker image
        run: |
          ./build-docker.sh onedocker -f
  ### Build emp_games image
  build_emp_games_image:
    name: Build Image
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Remove unused images
        run: |
          df -h
          docker image prune -af
          df -h

      - name: Build onedocker image
        run: |
          ./build-docker.sh emp_games -f
  ### Build onedocker image
  build_onedocker_image:
    name: Build Image
    runs-on: self-hosted
    needs: [build_data_processing_image, build_emp_games_image]
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Remove unused images
        run: |
          df -h
          docker image prune -af
          df -h

      - name: Build onedocker image
        run: |
          ./build-docker.sh onedocker -f
